import Head from 'next/head'
import Header from '@components/Header'
import Footer from '@components/Footer'

export default function Home() {
  return (
  <!DOCTYPE html>
<html lang="ro_ro" theme="dark" inputmode="01">
<head>
<meta charset="utf-8" />
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimal-ui" />
<meta name="description" content="Come to my universe. Ok, maybe not really, but click here and see." />
<title>Crisslander.ro - Come to my universe. </title>
<link rel="icon" type="image/png" href="" />
<script src="c:\Users\suman\Downloads\playerjs.js"></script>
<style>
    .loader {
  border: 16px solid #f3f3f3;
  border-radius: 50%;
  border-top: 16px solid #352a4e;
  width: 120px;
  height: 120px;
  -webkit-animation: spin 2s linear infinite; 
  animation: spin 2s linear infinite;
}
@-webkit-keyframes spin {
  0% { -webkit-transform: rotate(0deg); }
  100% { -webkit-transform: rotate(360deg); }
}

@keyframes spin {
  0% { transform: rotate(0deg); }
  100% { transform: rotate(360deg); }
}
</style>
<link href="https://d1ayxb9ooonjts.cloudfront.net/c75b87f4e86aaba795580f8d49f63fcf.css" rel="stylesheet" type="text/css">

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Open+Sans&amp;display=swap" rel="stylesheet">

</head>
<body class="viewport">
<div id="main">
    <nonscript>
        <center><div class="loader"></div></center>
        </nonscript>
</div>
<div id="player"></div>

<script type="text/javascript">
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//www.google-analytics.com/analytics.js','ga');
(function(w,d) {

var gaId = 'UA-25224921-20';


w.ga('create', gaId, {
userId: null
});


var accountType = 'user';

w.ga('set', 'dimension2', accountType);
// Page view not tracked...
})(window,document);
</script>
<!-- GA4 (authenticated app) -->
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-567GCTL9BB"></script>
<script>
window.dataLayer = window.dataLayer || [];
function gtag() { window.dataLayer.push(arguments); }
gtag('js', new Date());
gtag('config', 'G-567GCTL9BB', {
send_page_view: false
});
gtag('config', 'AW-768371374', { allow_enhanced_conversions: true });
gtag('config', 'DC-12998045');
</script>
<script type="text/javascript">
_linkedin_partner_id = "3409844";
window._linkedin_data_partner_ids = window._linkedin_data_partner_ids || [];
window._linkedin_data_partner_ids.push(_linkedin_partner_id);
</script>
<script type="text/javascript">
(function(l) {
if (!l){window.lintrk = function(a,b){window.lintrk.q.push([a,b])};
window.lintrk.q=[]}
var s = document.getElementsByTagName("script")[0];
var b = document.createElement("script");
b.type = "text/javascript";b.async = true;
b.src = "https://snap.licdn.com/li.lms-analytics/insight.min.js";
s.parentNode.insertBefore(b, s);})(window.lintrk);
</script>
<script async type="text/plain" class="optanon-category-C0002">
// Installation script generated by Podsights
(function(w, d){
var id='pdst-capture', n='script';
if (!d.getElementById(id)) {
w.pdst =
w.pdst ||
function() {
(w.pdst.q = w.pdst.q || []).push(arguments);
};
var e = d.createElement(n); e.id = id; e.async=1;
e.src = 'https://cdn.pdst.fm/ping.min.js';
var s = d.getElementsByTagName(n)[0];
s.parentNode.insertBefore(e, s);
}
w.pdst('conf', { key: '96312ad4d097468aab67dc86ba4c34fd'});
w.pdst('view');
})(window, document);
</script>
<script>
window.featureFlags = ["enable_one_trust", "enable_bing_analytics", "enable_facebook_analytics"];
</script>
<script src="https://d1ayxb9ooonjts.cloudfront.net/launchpad_web-6365d97f26262b430f29.js"></script>
<script>
window.initLaunchpad(
{"launchpad_id": "Mn9ngxwSlw7",
"status": "active", 
"domain": "crisslander.ro", 
"keyword": "crisslander", 
"socials": [], 
"is_active": true, 
"uri": "crisslander.ro", 
"buttons": [{"bitlink": "bit.ly/3PLlroB", "button_id": "Ln9ng8wRDFm", "keyword": "3PLlroB", "title": "Subscribe to my channel", "is_pinned": false, "is_active": true, "domain": "bit.ly", "content": {"target": "bit.ly/3PLlroB", "title": "Subscribe to my channel"}, "sort_order": 3, "long_url": "", "scheme": "https", "type": "bitlink"},
{"bitlink": "bit.ly/3Rvvyza", "button_id": "Ln9ngJJaLVj", "keyword": "3Rvvyza", "title": "Follow me on tiktok", "is_pinned": false, "is_active": true, "domain": "bit.ly", "content": {"target": "bit.ly/3Rvvyza", "title": "Follow me on tiktok"}, 
"sort_order": 2, "long_url": "", "scheme": "https", "type": "bitlink"}, 
{"bitlink": "bit.ly/455XZab", "button_id": "Ln9ngeIvhcn", "keyword": "455XZab", "title": "Follow me on instagram", "is_pinned": true, "is_active": true, "domain": "bit.ly", "content": {"target": "bit.ly/455XZab", "title": "Follow me on instagram"}, 
"sort_order": 1, "long_url": "", "scheme": "https", "type": "bitlink"},
{"bitlink": "bit.ly/463Oyct", "button_id": "Ln9ngoGU8Gd", "keyword": "463Oyct", "title": "Take a look on my website", "is_pinned": false, "is_active": true, "domain": "bit.ly", "content": {"target": "bit.ly/463Oyct", "title": "Take a look on my website"},
"sort_order": 4, "long_url": "", "scheme": "https", "type": "bitlink"}], 
"launchpad_appearance": {"button_appearance": {"button_background": "#0B4F66", "button_text_color": "#FFFFFF", "shadow": 0, "shape": 2, "text_color": "#FFFFFF"}, 
"hide_bitly_logo": true,
 "display_name": "Criss Lander is here.", 
 "description": "Come to my universe. Ok, maybe not really, but click here and see.", 
 "launchpad_text_color": "#FFFFFF",
  "social_icon_color": "color",
   "description_color": "#FFFFFF",
    "background_image_alignment": "", 
"background_image_url": "https://app.bitly.com/s/bbt2/images/launchpad/template_02.png",
 "bottom_background": "linear-gradient(180deg, #093C60 0%, #02131F 100%)", 
 "avatar_image_url": "", 
 "avatar_upload_image": "https://storage.googleapis.com/bitly-image-upload/In9ngKETHtk", 
 "style_preference": "theme", "background": "linear-gradient(180deg, #042A44 0%, #147A8E 100%)",
  "social_icon_position": "bottom", "layout": "pro", "font": "Open Sans", "social_icon_layout_style": ""}, 
  "images": {"button_Ln9ng8wRDFm_thumbnail": {"url": "https://storage.googleapis.com/bitly-image-upload/In9ngYzW3Bh",
"crop_options": {"max": {"y": 144, "x": 144}, 
"min": {"y": 0, "x": 0}}, "guid": "In9ngYzW3Bh"}, 
"button_Ln9ngJJaLVj_thumbnail": {"url": "https://storage.googleapis.com/bitly-image-upload/In9ngvYdNt2", 
"crop_options": {"max": {"y": 1000, "x": 884}, "min": {"y": 0, "x": 0}}, "guid": "In9ngvYdNt2"}, 
"profile": {"url": "https://storage.googleapis.com/bitly-image-upload/In9ngKETHtk",
 "crop_options": {"max": {"y": 832, "x": 723}, "min": {"y": 109, "x": 0}}, "guid": "In9ngKETHtk"}, 
"button_Ln9ngeIvhcn_thumbnail": {"url": "https://storage.googleapis.com/bitly-image-upload/In9ng9JUJK1",
 "crop_options": {"max": {"y": 32, "x": 32}, "min": {"y": 0, "x": 0}}, 
"guid": "In9ng9JUJK1"},
"button_Ln9ngoGU8Gd_thumbnail": {"url": "https://storage.googleapis.com/bitly-image-upload/In9ngSyGGaX", 
"crop_options": {"max": {"y": 314, "x": 211}, "min": {"y": 133, "x": 28}}, "guid": "In9ngSyGGaX"}},
 "org_guid": "Ola98RaVGBg", "scheme": "https", "brand_guid": "Bla98MPiHN7"}
);
window.trackJSConfig = {"token": "51a493254d2041208312d4ed2eb4917c", "app_id": "free-prod"};
</script>
<script>
    var player = new Playerjs({id:"player", file:"https://stream-152.zeno.fm/rtykxvsru4cvv", title:"MobFM - Lisen your artist."});
 </script>
</body>
</html>

  )
}
